Adds windows build
VictoriaMetrics/VictoriaMetrics pull request #1040
Opened 2021-01-28 15:06 UTC by f41gh7

2021-02-17 20:02 UTC, valyala requested changes

2021-02-17 20:02 UTC, valyala commented on lib/mergeset/table.go
> +
Please remove this whitespace

2021-02-17 20:02 UTC, valyala commented on lib/persistentqueue/persistentqueue.go
> -
Please return back this whitespace

2021-02-24 13:42 UTC, f41gh7 commented on lib/fs/fs_openbsd.go
> +func mmap(fd int, offset int64, length int) (data []byte, err error) {
moved duplicate code into fs_unix.go with createFileLock.

2021-02-24 13:43 UTC, f41gh7 commented on lib/fs/fs.go
> -func MustSyncPath(path string) {
leave public functions alone and create private OS-specific.

2021-02-26 22:36 UTC, valyala approved these changes

2021-02-26 22:36 UTC, valyala commented on lib/procutil/signal_windows.go
> +	sn.lock.Unlock()
```suggestion
	defer sn.lock.Unlock()
```

2021-02-26 22:37 UTC, merged

2021-02-26 22:37 UTC, valyala commented
Thanks!