Added some explanation to vmctl docs
VictoriaMetrics/VictoriaMetrics pull request #1217
Opened 2021-04-14 09:56 UTC by denisgolius

Added explanation that vmctl do not make snapshot from Prometheus when run migration data

2021-04-14 17:03 UTC, hagen1778 requested changes
Thanks for doing this! I think we can slightly simplify docs, see my comments.

2021-04-14 17:03 UTC, hagen1778 commented on docs/vmctl.md
>  See `./vmctl prometheus --help` for details and full list of flags.
```suggestion
See `./vmctl prometheus --help` for details and full list of flags. Also see Prometheus related articles [here](#articles).
```

2021-04-15 09:34 UTC, denisgolius commented
I agree with you.

2021-04-15 17:40 UTC, hagen1778 approved these changes

2021-04-15 17:40 UTC, merged

2021-04-15 17:40 UTC, hagen1778 commented
Thank you!