vmalert: enable configuring explicit path
VictoriaMetrics/VictoriaMetrics pull request #1536
Opened 2021-08-13 08:06 UTC by alxric

Currently, whatever you configure as `remoteWrite.url` , the path `/api/v1/write` will always be appended to it.
This causes problems when your remote host for one reason or the other does not serve that path, so this PR will add the option to override it with an absolute path if so desired, otherwise keep using the current behaviour.

2021-08-16 08:40 UTC, f41gh7 commented
Hm, probably, its better to introduce flag -  `-remoteWrite.disablePathAppend`, which would control path concatenation for remoteWrite?
  And with `./bin/vmalert -remoteWrite.url=http://some-url:8428/api/v2/write -remoteWrite.disablePathAppend` it would be possible to use absolute url for remoteWrite.

@hagen1778  WDYT?

2021-08-16 09:19 UTC, hagen1778 commented
I agree with @f41gh7 - `-remoteWrite.disablePathAppend` will simplify the change while allowing the same functionality. @alxric, do you have any objections?

2021-08-16 09:34 UTC, alxric commented
> I agree with @f41gh7 - `-remoteWrite.disablePathAppend` will simplify the change while allowing the same functionality. @alxric, do you have any objections?

Nope, none at all. I agree, that is a cleaner approach. Pushed suggested changes

2021-08-16 09:46 UTC, hagen1778 requested changes
Thanks! Small changes

2021-08-16 09:46 UTC, hagen1778 commented on app/vmalert/README.md
> +    	Optionally disable appending '/api/v1/write' to the remoteWrite url, enabling configuring an absolute path
```suggestion
     Whether to disable automatic appending of '/api/v1/write' path to the configured -remoteWrite.url.
```

2021-08-16 09:46 UTC, hagen1778 commented on app/vmalert/remotewrite/init.go
> +	disablePathAppend = flag.Bool("remoteWrite.disablePathAppend", false, "Optionally disable appending '/api/v1/write' to the remoteWrite url, "+
```suggestion
	disablePathAppend = flag.Bool("remoteWrite.disablePathAppend", false, "Whether to disable automatic appending of '/api/v1/write' path to the configured -remoteWrite.url.")
```

2021-08-16 09:46 UTC, hagen1778 commented on app/vmalert/remotewrite/remotewrite.go
> +	// DisablePathAppend can be used to not automatically append '/api/v1/write' to the remote write url
```suggestion
	// DisablePathAppend prevents appending of '/api/v1/write' path to the addr
```

2021-08-16 09:46 UTC, hagen1778 commented on docs/vmalert.md
> +    	Optionally disable appending '/api/v1/write' to the remoteWrite url, enabling configuring an absolute path
```suggestion
    	Whether to disable automatic appending of '/api/v1/write' path to the configured -remoteWrite.url.
```

2021-08-16 10:06 UTC, hagen1778 commented
Build fails. Looks like in suggestion I broke the line format.

2021-08-16 10:12 UTC, alxric commented
> Build fails. Looks like in suggestion I broke the line format.

Ah, missed to verify that I could build locally after changes. Should be fine now

2021-08-16 11:20 UTC, merged

2021-08-16 11:21 UTC, hagen1778 commented
Thanks for contribution!

2021-08-19 10:54 UTC, valyala commented
FYI, the pull request has been included in [vmalert v1.64.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).