Update FAQ.md
VictoriaMetrics/VictoriaMetrics pull request #1765
Opened 2021-10-29 16:53 UTC by YuriKravetc

Adding explanation "Why do same metrics have differences in VictoriaMetrics and Prometheus dashboards?"

2021-12-02 10:20 UTC, hagen1778 requested changes
Please, see my comment

2021-12-02 10:20 UTC, hagen1778 commented on docs/FAQ.md
> +## Why do same metrics have differences in VictoriaMetrics and Prometheus dashboards?
The explanation is not full. There are two aspects to consider:
1. Difference in stored raw time series. Due to different compressions algorithms, VM may reduce precision for float values with more than 12 significant decimal digits. Please, read more about this here https://valyala.medium.com/evaluating-performance-and-correctness-victoriametrics-response-e27315627e87
2. Difference in query responses. Please read more here https://medium.com/@romanhavronenko/victoriametrics-promql-compliance-d4318203f51e

2021-12-16 06:44 UTC, hagen1778 approved these changes

2021-12-16 06:44 UTC, hagen1778 commented on docs/FAQ.md
> +There is a difference in stored raw time series. Due to different compression algorithms, VM may reduce precision for float values with more than 12 significant decimal digits. Please see [this artic
```suggestion
There could be a slight difference in stored values for time series. Due to different compression algorithms, VM may reduce precision for float values with more than 12 significant decimal digits. Please see [this article](https://valyala.medium.com/evaluating-performance-and-correctness-victoriametrics-response-e27315627e87)
```

2021-12-16 06:44 UTC, hagen1778 commented on docs/FAQ.md
> +There is a slight difference in logic and query responses. Please see [this article](https://medium.com/@romanhavronenko/victoriametrics-promql-compliance-d4318203f51e)
```suggestion
The query engine may behave differently for some functions. Please see [this article](https://medium.com/@romanhavronenko/victoriametrics-promql-compliance-d4318203f51e)
```

2021-12-20 11:42 UTC, valyala approved these changes

2021-12-20 11:43 UTC, merged

2021-12-20 11:43 UTC, valyala commented
Thanks!