app/vmselect: adds proxy for rules API
VictoriaMetrics/VictoriaMetrics pull request #2516
Opened 2022-04-28 21:08 UTC by f41gh7

It allows to visualization for alerting rules at grafana
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1739

2022-05-02 08:33 UTC, hagen1778 requested changes

2022-05-02 08:33 UTC, hagen1778 commented on app/vmselect/main.go
> +	vmalertProxyURL      = flag.String("vmalert.proxyURL", "", "Optional relative URL for proxy grafana rules and alerts requests to the vmalert, e.g. http://vmalert:8880.")
```suggestion
	vmalertProxyURL      = flag.String("vmalert.proxyURL", "", "Optional relative vmalert's URL for proxying  `api/v1/rules` or `/alerts` requests. Set this flag for accessing vmalert's UI or API (e.g. for Grafana rules engine) through the vmselect,  e.g. http://vmalert:8880.")
```

2022-05-03 13:26 UTC, valyala commented on app/vmselect/main.go
> +		fmt.Fprintf(w, "%s", stubResponse)
```suggestion
		_, _ = io.WriteString(w, stubResponse)
```

2022-05-03 17:54 UTC, valyala approved these changes

2022-05-03 17:55 UTC, merged

2022-05-03 17:55 UTC, valyala commented
Thanks!