Update alerts.yml
VictoriaMetrics/VictoriaMetrics pull request #2760
Opened 2022-06-20 13:24 UTC by YuriKravetc

2022-06-20 14:06 UTC, hagen1778 requested changes

2022-06-20 14:06 UTC, hagen1778 commented on deployment/docker/alerts.yml
> +        expr: sum(increase(vm_log_messages_total{level!="error"}[5m])) by (job, instance) > 0
it should be `level!="error"`
otherwise, it rules out all `error` messages and will alert only on `info` and `warning`

2022-06-20 14:11 UTC, hagen1778 commented
@YuriKravetc please update commit message with explanation why this change is needed
please also see https://github.com/erlang/otp/wiki/writing-good-commit-messages

Please see example here https://github.com/VictoriaMetrics/VictoriaMetrics/commit/7cd371f08f19058c010094cfb30674227a811024

2022-06-20 14:44 UTC, merged

2026-01-25 16:58 UTC, valyala commented
FYI, the commit 5632ccc64a48377c4ffad7396a5d3a2bd110d391 returned back the filter for TooManyLogs alert to `level!="info"`, in order to be consistent with [the official dashboards for VictoriaMetrics components](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/dashboards), which use the `level!="info"` filter instead of `level="error"` filter for the `vm_log_messages_total` metric.

Instead of ignoring `level="warn"` logs in this alerting rule, it is better to figure out how to reduce the rate of such logs at the code location which generates them.