vmalert: mark some url flags as sensitive
VictoriaMetrics/VictoriaMetrics pull request #2965
Opened 2022-08-08 15:00 UTC by mble

Other components, such as `vmagent`, mark these flags as sensitive and
hide them from the `/metrics` endpoint by default. This commit adds
similar handling to the `vmalert` component, hiding them by default, to
prevent logging of secrets inappropriately.

Showing of these values is controlled by an additional flag.

Follow up to https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2947

2022-08-10 14:48 UTC, hagen1778 requested changes

2022-08-10 14:48 UTC, hagen1778 commented on app/vmalert/datasource/init.go
> +	showDatasourceURL = flag.Bool("remoteWrite.showURL", false, "Whether to show -datasource.url in the exported metrics. "+
```suggestion
	showDatasourceURL = flag.Bool("datasource.showURL", false, "Whether to show -datasource.url in the exported metrics. "+
```

2022-08-10 15:07 UTC, mble commented on app/vmalert/datasource/init.go
> +	showDatasourceURL = flag.Bool("remoteWrite.showURL", false, "Whether to show -datasource.url in the exported metrics. "+
Clearly I was asleep at the wheel.

2022-08-11 07:56 UTC, hagen1778 approved these changes
Thank you!

2022-08-11 07:56 UTC, merged

2022-08-30 21:44 UTC, valyala commented
FYI, this pull request has been included in [vmalert v1.79.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.3).

2022-08-31 01:14 UTC, valyala commented
FYI, this pull request has been included in [vmalert v1.81.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).