vmbackup: update AWS SDK to v2
VictoriaMetrics/VictoriaMetrics pull request #3174
Opened 2022-09-27 14:35 UTC by zekker6

2022-09-30 06:09 UTC, valyala requested changes

2022-09-30 06:09 UTC, valyala commented on lib/backup/s3remote/s3.go
> +		if errors.As(err, &nsk) {
Probably, it would be better using `errors.Is()` here, since `nsk` isn't used here.

2022-09-30 07:22 UTC, zekker6 commented on lib/backup/s3remote/s3.go
> -		// hack for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1449
I've tested this on self-hosted Minio server with `AWS_REGION` not being set and set to empty string, SDK uses region to `us-west-1` by default.

2022-10-01 14:12 UTC, valyala approved these changes

2022-10-01 14:12 UTC, merged

2022-10-01 14:12 UTC, valyala commented
@zekker6 , thanks for the upgrade of AWS SDK from v1 to v2!

2022-10-01 14:46 UTC, valyala commented
@zekker6 , could you address the following errors in the enterprise repository of VictoriaMetrics?

```
lib/backup/s3remote/s3.go:290:13: undefined: s3manager
lib/backup/s3remote/s3.go:290:66: undefined: aws.BackgroundContext
lib/backup/s3remote/s3.go:290:87: undefined: s3manager
lib/backup/s3remote/s3.go:356:15: fs.s3.ListObjectsV2Pages undefined (type *s3.Client has no field or method ListObjectsV2Pages)
```

2022-10-13 07:32 UTC, valyala commented on lib/backup/s3remote/s3.go
> -		// hack for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1449
FYI, the related pull request - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3224