vmui: limit the number of decimal places to 10 characters
VictoriaMetrics/VictoriaMetrics pull request #3258
Opened 2022-10-23 15:48 UTC by Loori-R

A large number of decimal places in the values on the chart breaks the application.
Limited the number of decimal places to 10.

2022-10-24 07:30 UTC, dmitryk-dk approved these changes
LGTM!

2022-10-24 18:18 UTC, valyala requested changes

2022-10-24 18:18 UTC, valyala commented on app/vmui/packages/vmui/src/components/CustomPanel/Views/GraphView.tsx
> +      return parseFloat(`${whole}.${decimal.slice(0, 10)}`);
This fix breaks if the request returns small values near zero. For example, the request `rand()*1e-20` would draw zero line, while it is expected that it draws random values line in the range `[0 ... 1e-20]`.

The original issue is in [uPlot library](https://github.com/leeoniya/uPlot) - it stops working when drawing time series with small difference between time series values comparing to the average series value. E.g. if `abs(avg(values)) > range(values) * 1e10` . For example, it freezes when drawing the response for `1e8 + rand()*1e-7` [MetricsQL query](https://docs.victoriametrics.com/MetricsQL.html).

The solution is to report the bug to the upstream [uPlot repository](https://github.com/leeoniya/uPlot) and fix the bug there. In the meantime vmui can provide a workaround, which would replace time series values with their average value before passing them to uPlot if `abs(avg(values)) > range(values)*1e10`.

2022-10-25 23:43 UTC, valyala approved these changes

2022-10-25 23:43 UTC, merged

2022-10-25 23:43 UTC, valyala commented
@Loori-R , thanks!