Add Understand Your Setup Size Guide
VictoriaMetrics/VictoriaMetrics pull request #3572
Opened 2022-12-29 22:39 UTC by tenmozes

Signed-off-by: Artem Navoiev <tenmozes@gmail.com>

2022-12-30 10:32 UTC, hagen1778 requested changes
Please, use some spell-checking for this text to fix the typos.

2022-12-30 10:32 UTC, hagen1778 commented on docs/guides/understand-your-setup-size.md
> +
```suggestion
Use the following query to track the churn rate for the last 24h in Prometheus:

**sum(sum_over_time(scrape_series_added[24h]))**

For VictoriaMetrics query would be the following:

**sum(increase(vm_new_timeseries_created_total[24h]))**
```

2022-12-30 10:32 UTC, hagen1778 commented on docs/guides/understand-your-setup-size.md
> +
```suggestion

For those who are familiar with Prometheus, we recommend reading [Prometheus storage: technical terms for humans](https://valyala.medium.com/prometheus-storage-technical-terms-for-humans-4ab4de6c3d48).

```

2022-12-30 10:32 UTC, hagen1778 commented on docs/guides/understand-your-setup-size.md
> +For Ingestion Rate calculation, you need to know how many time series you pull or push and how often you save them into VictoriaMetrics. To be more specific, the formula is the Number Of Active Time
```suggestion
For Ingestion Rate calculation, you need to know how many time series you pull or push in VictoriaMetrics per second. To be more specific, the formula is the Number Of Active Time Series / Metrics Collection Interval.
```

2022-12-30 10:32 UTC, hagen1778 commented on docs/guides/understand-your-setup-size.md
> +### Terminology
Please note, ## is then used by docs engine to build the hierarchy tree. Skipping levels or having too much levels can look weird.

2023-01-04 23:16 UTC, tenmozes commented on docs/guides/understand-your-setup-size.md
> +### Terminology
I've done that intentionally Terminology is a sub-item of the first paragraph. Calculation is the next important item

2023-01-05 08:42 UTC, hagen1778 commented on docs/guides/understand-your-setup-size.md
> +### Terminology
So you have level-1 item. And the next item is level-3. Why not level-2?

2023-01-05 09:07 UTC, tenmozes commented on docs/guides/understand-your-setup-size.md
> +### Terminology
fixed, thanks

2023-01-05 13:56 UTC, hagen1778 approved these changes
thank you!

2023-01-05 13:56 UTC, merged