docs: add documentation of user management on managed-vm
VictoriaMetrics/VictoriaMetrics pull request #3714
Opened 2023-01-26 16:19 UTC by dmitryk-dk

Added documentation for user management on managed-vm. 
Refactored struct of the project.

Signed-off-by: dmitryk-dk [d.kozlov@victoriametrics.com](mailto:d.kozlov@victoriametrics.com)

2023-01-26 21:40 UTC, tenmozes requested changes

2023-01-26 21:40 UTC, tenmozes commented on docs/managed-victoriametrics/quickstart.md
> +  <img src="../assets/images/managed/quickstart/restore-password.png" width="800">
start with absolute path /

2023-01-27 09:31 UTC, dmitryk-dk commented on docs/managed-victoriametrics/quickstart.md
> +  <img src="../assets/images/managed/quickstart/restore-password.png" width="800">
fixed

2023-01-27 12:07 UTC, tenmozes approved these changes

2023-01-27 12:07 UTC, merged