lib/storage: creates parts.json on start-up if it not exists.
VictoriaMetrics/VictoriaMetrics pull request #4450
Opened 2023-06-14 10:32 UTC by f41gh7

It fixes migrations from versions below v1.90.0.
Previously parts.json was created only after successful merge. But if merge was interruped for some reason (OOM or shutdown), parts.json wasn't created and partitions left after interruped merge weren't properly deleted. Since VM cannot check if it must be removed or not. https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4336

2023-06-14 11:24 UTC, hagen1778 requested changes

2023-06-14 11:24 UTC, hagen1778 commented on lib/mergeset/table.go
> +		mustWritePartNames(pws, partNamesPath)
```suggestion
		mustWritePartNames(pws, path)
```

2023-06-14 11:24 UTC, hagen1778 commented on lib/storage/partition.go
> +		mustWritePartNames(smallParts, bigParts, partNamesPath)
```suggestion
		mustWritePartNames(smallParts, bigParts, path)
```

2023-06-14 15:09 UTC, hagen1778 requested changes

2023-06-14 15:09 UTC, hagen1778 commented on lib/storage/partition.go
> +		mustWritePartNames(smallParts, bigParts, path)
```suggestion
		mustWritePartNames(smallParts, bigParts, smallPartsPath)
```
sorry, my prev suggestion was incorrect

2023-06-15 09:02 UTC, hagen1778 approved these changes
LGTM!

2023-06-15 09:19 UTC, merged

2023-06-26 08:49 UTC, jeremychauvet commented
Hello @hagen1778 👋🏼 
Did you plan to release this fix soon? I'm also facing the issue #4336

2023-06-27 05:46 UTC, hagen1778 commented
Hello @jeremychauvet! The release is likely to happen in the next two weeks.

2023-07-03 03:46 UTC, andyli029 commented
@hagen1778 @f41gh7 
the pr is not merged to the cluster source code: https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster

2023-07-03 04:51 UTC, f41gh7 commented
> @hagen1778 @f41gh7 The pr is not merged to the cluster source code: https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster

It's a patch release on top of v1.91.2. With bug fixes only. Later we're going to merge changes into cluster branch and release v1.92.0. 

 Source code could be found at linked tag https://github.com/VictoriaMetrics/VictoriaMetrics/commits/v1.91.3-cluster

2023-07-03 07:14 UTC, andyli029 commented
> > @hagen1778 @f41gh7 The pr is not merged to the cluster source code: https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster
> 
> It's a patch release on top of v1.91.2. With bug fixes only. Later we're going to merge changes into cluster branch and release v1.92.0.
> 
> Source code could be found at linked tag https://github.com/VictoriaMetrics/VictoriaMetrics/commits/v1.91.3-cluster

Thanks.