vmui: add tip to Explore Metrics page
VictoriaMetrics/VictoriaMetrics pull request #4615
Opened 2023-07-11 11:48 UTC by Loori-R

- Changed tab name to `Explore Prometheus Metrics`
- Added a tip that explains the page's intended purpose
- Tooltip can be toggled to show/hide (state is preserved in `localStorage`)

<img width="1452" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/29711459/3706cd9e-6075-4533-a388-cfd4b1e0c654">

#4248

2023-07-12 08:08 UTC, dmitryk-dk approved these changes

2023-07-14 12:09 UTC, hagen1778 requested changes

2023-07-14 12:09 UTC, hagen1778 commented on app/vmui/packages/vmui/src/components/ExploreMetrics/ExploreMetricsHeader/ExploreMetricsHeader.tsx
> +              Prometheus metrics always carry <code>job</code> and <code>instance</code> labels,
```suggestion
              Prometheus metrics always contain <code>job</code> and <code>instance</code> labels,
```

2023-07-14 12:09 UTC, hagen1778 commented on app/vmui/packages/vmui/src/components/ExploreMetrics/ExploreMetricsHeader/ExploreMetricsHeader.tsx
> +              which this page was initially created to handle.
```suggestion
              and this page relies on them as filters.
```

2023-07-14 12:09 UTC, hagen1778 commented on app/vmui/packages/vmui/src/components/ExploreMetrics/ExploreMetricsHeader/ExploreMetricsHeader.tsx
> +              Metrics without a <code>job</code> selection may mislead due to their diverse values.
```suggestion
```

2023-07-14 12:09 UTC, hagen1778 commented on app/vmui/packages/vmui/src/components/ExploreMetrics/ExploreMetricsHeader/ExploreMetricsHeader.tsx
> +              Prometheus metrics always carry <code>job</code> and <code>instance</code> labels,
Would be nice to link the convention here https://prometheus.io/docs/concepts/jobs_instances/

2023-07-18 09:44 UTC, hagen1778 approved these changes
Thanks!

2023-07-18 09:44 UTC, merged