deployment/logs-benchmark: add suite for Loki
VictoriaMetrics/VictoriaMetrics pull request #5165
Opened 2023-10-12 07:48 UTC by zekker6

2023-10-12 07:49 UTC, tenmozes commented on deployment/logs-benchmark/docker-compose-elk.yml
> +    image: golang:1.20-alpine
1.21.3?

2023-10-12 07:50 UTC, tenmozes requested changes
We need to update https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/logs-benchmark#how-to-run and add ELK and Loki sections

2023-10-12 07:51 UTC, zekker6 commented
Isn't it covered in step 4 of "how to run"?

2023-10-12 07:52 UTC, tenmozes commented on deployment/logs-benchmark/readme.md
> +Benchmark compares VictoriaLogs with ELK stack and Grafana Loki.
Can we be consistent with the docs, have general readme with loki and elk or have a readme per benchmark
I recommend to keep everything in one readme as far as we have only elk and loki

2023-10-13 11:13 UTC, tenmozes approved these changes

2023-10-13 13:13 UTC, merged