app/vmagent: adds pubsub integration for enterprise version
VictoriaMetrics/VictoriaMetrics pull request #5358
Opened 2023-11-20 17:24 UTC by f41gh7

2023-11-22 11:51 UTC, tenmozes commented on app/vmagent/README.md
> +These formats can be configured with `-gcp.pubsub.subscribe.defaultMessageFormat` or `-gcp.pubsub.subscribe.topicSubscription.messageFormat` command-line options. The following formats are supported:
`-gcp.pubsub.subscribe.defaultMessageFormat` and `-gcp.pubsub.subscribe.topicSubscription.messageFormat` allow to configure the message format 
We support the following options:

2023-11-22 11:57 UTC, tenmozes requested changes

2023-11-22 11:57 UTC, tenmozes commented on app/vmagent/README.md
> +by passing multiple `-gcp.pubsub.subscribe.topicSubscription` command-line flags to `vmagent`.
You can configure the multiple topics by specifying `-gcp.pubsub.subscribe.topicSubscription` command-line flags in `vmagent`

2023-11-22 11:57 UTC, tenmozes commented on app/vmagent/README.md
> +`vmagent` uses standard google authorization mechanism for topic access. It's possible to specify credentials directly via flag `-gcp.pubsub.subscribe.credentialsFile=`.
`vmagent` uses a standard Google authorization mechanism for topic access. It's possible to specify credentials directly via the flag `-gcp.pubsub.subscribe.credentialsFile=`.

2023-11-22 11:57 UTC, tenmozes commented on app/vmagent/README.md
> +#### Consume from multiple topics
Consume metrics from...

2023-11-22 11:57 UTC, tenmozes commented on app/vmagent/README.md
> +It's possible to configure message consumption with multiple topics. In this case, command-line flag arguments must have the same position at corresponding values.
consumption from multiple topics.

2023-11-23 19:10 UTC, merged

2023-11-23 19:10 UTC, valyala commented
@f41gh7 , thanks for the docs!