FIX sort order in bottomk
VictoriaMetrics/VictoriaMetrics pull request #5509
Opened 2023-12-21 08:35 UTC by xiaozongyang

try to fix [#5506]

2023-12-21 08:37 UTC, xiaozongyang commented
Hi @valyala @hagen1778 @f41gh7, would you mind checking this issue and review this MR?

2023-12-22 05:14 UTC, xiaozongyang commented
This fix doesn't work

2023-12-22 12:16 UTC, hagen1778 reviewed
Looks good to me!
Would you mind fixing linter errors? You can invoke the full check locally by running `make test`

2023-12-23 06:42 UTC, xiaozongyang commented
sure, I will fix the lint errors in next commit

2023-12-25 02:45 UTC, xiaozongyang commented
Hi @hagen1778, these lint errors have been fixed, but there is a fatal error about unit test of `github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.go`. I've no idea about fixing this error, would you mind helping check whether it's cause by this PR or not? Or just ignore this error temperately?
If you have some suggestions to fix this error, I'd like to try to fix it !
cc @valyala

2023-12-26 11:21 UTC, xiaozongyang commented
ping @hagen1778, lint and test errors have been fixed already, would you mind reviewing this PR once more?

2023-12-27 10:22 UTC, xiaozongyang commented
@hagen1778 @valyala Merry Christmas  you guys, and have a nice holiday. It's ok to review this PR later.

2024-01-10 13:14 UTC, hagen1778 requested changes
Thanks! Please see my comments

2024-01-10 13:14 UTC, hagen1778 commented on app/vmselect/promql/aggr.go
> +		}
I think it would be more transparent, if we'll just filter out all NaNs before applying sorting. wdyt?

2024-01-10 13:14 UTC, hagen1778 commented on lib/filestream/filestream.go
> +	offset uint64 // nolint
It is better to revert changes not related to the changes in app/vmselect/promql package.

2024-01-16 00:19 UTC, merged

2024-01-16 00:19 UTC, valyala commented
@xiaozongyang , thanks for the pull request!

2024-01-16 23:52 UTC, valyala commented
The pull request has been included in [v1.93.10 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.10).

2024-01-30 22:41 UTC, valyala commented
FYI, the pull request has been included in [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html).