dashboards/victoria-metrics-single: allow selecting multiple instance values
VictoriaMetrics/VictoriaMetrics pull request #5870
Opened 2024-02-26 07:28 UTC by zekker6

Allowing to select multiple instance IPs makes it much easier to view metrics for longer periods of time in dynamic environments such as Kubernetes. In k8s update will also cause IP to change making it harder to use dashboard to check the status.

See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5869

2024-03-18 13:17 UTC, hagen1778 commented
The change is not correct, as many panels in the dashboard assume there is one instance always. 
For example, panel `Memory usage ($instance)` has many queries with `sum` aggregator. Summing this metric for multiple instance is not correct. We need to ensure that dashboard works correctly if there are more than 1 instance within same job running in the same time.

2024-03-28 14:37 UTC, hagen1778 requested changes
Still requires changes. See issues with 2 VM instances on a single dashboard below:
<img width="498" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/22263358-d819-49d9-840b-9a60a1d067eb">
<img width="674" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/fe9e85b3-0c67-479e-9ee3-0b5d74d39442">

No need to add something different to the instance name in legend below
<img width="652" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/eb55d445-fcef-4d25-b7d2-8f851c6f668b">
<img width="672" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/dc68e6f2-ef4b-46e2-acc9-d498734f3698">

Flags panel doesn't show to which instance it belongs
<img width="665" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/b5fe64c1-ebb4-4721-a719-a067d3cf7878">


duplicates for limits
<img width="655" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/41db83b6-5998-4f48-84d6-1dbe36763226">





---------------


In general, I'm not very happy with this change, as it contradicts to the dashboard design. With cluster and with single dashboards the assumption was that we observe one specific system. Hence, all resources, all characteristics belong to one specific system. For example, in cluster dashboard you have LSM parts belonging to this cluster. With this change if there are 2 instances we have the following:
<img width="663" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/78c7c512-a437-41b5-ab3a-d7a5463c1f6d">

The same is related to other things. For example 
<img width="273" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/b7270ed5-3f17-4b05-af78-c1d6faa7fa0e">
Is this average bytes-per-point for all instances? Is this correct to show average value?

2024-03-29 12:08 UTC, zekker6 commented
> In general, I'm not very happy with this change, as it contradicts to the dashboard design. With cluster and with single dashboards the assumption was that we observe one specific system. Hence, all resources, all characteristics belong to one specific system.

The primary use-case for this change is to allow using this dashboard with environments where instance label can change, such as k8s or other dynamic environments. Dashboard will still be used to observe the state of one system, but the instance label can change. 
Because of this with the current state of dashboard there is no way to compare resource usage before and after upgrade without either tweaking the query manually or opening 2 dashboards side by side.

Maybe you can see another way to update the dashboard to cover this use-case?

2024-04-29 08:33 UTC, hagen1778 approved these changes

2024-04-29 08:34 UTC, merged