lib/mergeset: adds tracking for indexdb records drop
VictoriaMetrics/VictoriaMetrics pull request #6297
Opened 2024-05-17 13:29 UTC by f41gh7

It allows to create alert for possible item drops at indexdb. It may happen, if ingested metric size exceeds max indexdb item size.

2024-05-20 06:40 UTC, zekker6 approved these changes
LGTM

2024-05-20 06:40 UTC, zekker6 commented on app/vmstorage/main.go
> +	metrics.WriteCounterUint64(w, `vm_indexdb_items_dropped_total{reason="too_long_item"}`, m.IndexDBMetrics.TooLongItemsDroppedTotal)
nit:
```suggestion
	metrics.WriteCounterUint64(w, `vm_indexdb_items_dropped_total{reason="too_long_item"}`, idbm.TooLongItemsDroppedTotal)
```

2024-05-20 11:59 UTC, hagen1778 requested changes
@f41gh7 would you mind adding an alerting rule as well?

2024-05-24 12:50 UTC, hagen1778 commented
@f41gh7 please see my follow-up here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6297/commits/c78adacde10458afdb86001a99e93a76828355ea

2024-05-24 12:54 UTC, hagen1778 approved these changes

2024-05-24 12:55 UTC, merged

2024-07-15 21:41 UTC, valyala commented
@f41gh7 , see the follow-up commit 832e0886595775784053cd89f2544350464d13b9