Multitenant queries
VictoriaMetrics/VictoriaMetrics pull request #6346
Opened 2024-05-24 13:28 UTC by zekker6

### Describe Your Changes

Added an ability to query data across multiple tenants. See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1434

Currently, the following endpoints work with multi-tenancy:
- `/prometheus/api/v1/query`
- `/prometheus/api/v1/query_range`
- `/prometheus/api/v1/series`
- `/prometheus/api/v1/labels`
- `/prometheus/api/v1/label/<label_name>/values`
- `/prometheus/api/v1/status/active_queries`
- `/prometheus/api/v1/status/top_queries`
- `/vmui`

A note regarding VMUI: endpoints such as `active_queries` and `top_queries` have been updated to indicate whether query was a single-tenant or multi-tenant, but UI needs to be updated to display this info.
cc: @Loori-R 

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

2024-06-28 00:13 UTC, f41gh7 commented on app/vmselect/multitenant/filters.go
> +func ApplyFiltersToTenants(tenants, filters []string) ([]*auth.Token, error) {
I think, behavior must be consistent with vminsert - if neither vm_account_id nor  vm_project_id is defined for filters - execute request to the 0:0 tenant (fast path)

2024-06-28 10:38 UTC, f41gh7 commented on app/vmselect/prometheus/prometheus.go
> +	if err = executeAcrossTenants(qt, at, cp, func(qt *querytracer.Tracer, at *auth.Token, _ bool) error {
It's better to move executeAcrossTenants to netstorage level and add tenant related labelsl to the blocks parsing.

 It allows to aggregate metrics over tenants properly.

2024-07-01 09:49 UTC, f41gh7 commented on app/vmselect/promql/eval_test.go
> +	f(`sum_over_time(rate(foo{vm_account_id="1",a="b"}[5m])[5m:1m])`, `sum_over_time(rate(foo{a="b"}[5m])[5m:1m])`, []string{`{vm_account_id="1"}`})
it'd be great to have a test for the following expression: 

```
up{vm_account_id="5"} + up{vm_project_id="11"} + sum(rate(up{vm_account_id="22"}))
```

2024-07-29 10:25 UTC, pmatuszak approved these changes

2024-07-29 10:28 UTC, pmatuszak approved these changes

2024-08-22 10:18 UTC, FOWind commented
it's unable to eval number with this pr
![image](https://github.com/user-attachments/assets/aa68d262-b53c-4daa-9c73-7c1139685d2c)

2024-08-22 11:14 UTC, zekker6 commented
@FOWind thank you for sharing, I'm currently working on quite large re-write for this PR and will make sure to check this use case as well.

2024-08-26 10:58 UTC, zekker6 commented
@FOWind This PR have been updated with a new implementation which also fixes an issue with number evaluation you've shared. You can find a pre-built image to run some tests here - [victoriametrics/vmselect:heads-multitenant-queries-0-gfdbd484883](https://hub.docker.com/layers/victoriametrics/vmselect/heads-multitenant-queries-0-gfdbd484883/images/sha256-9723cdef1916021851fb3322b1b893f12b286d47ee44356a1bc180f6d3ae7f16?context=explore)

If you'll encounter any other issues please post a comment here and we'll get it fixed, thank you for the feedback!

2024-08-26 17:57 UTC, zekker6 commented
You can find a demo datasource which is using version of vmselect build from this PR [here](https://play-grafana.victoriametrics.com/explore?schemaVersion=1&panes=%7B%22pcw%22:%7B%22datasource%22:%22P8FF7EDDF703E5E58%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22up%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P8FF7EDDF703E5E58%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1&chunkNotFound).

Feel free to try out queries and/or grouping of data across tenants. Feedback is much appreciated.

2024-09-05 16:28 UTC, f41gh7 commented on app/vmselect/prometheus/prometheus.go
> +	err = populateAuthTokens(qt, ec, at, deadline)
It's better to parse tenant related labels only once, during query request to the storage. 

 It ll make code simpler and allow to use current cache implementation.

2024-09-05 16:30 UTC, f41gh7 commented on lib/storage/search.go
> +func (sq *SearchQuery) Exec(qt *querytracer.Tracer, cb func(qt *querytracer.Tracer, requestData []byte, t TenantToken) any) []any {
It's better to move `Exec` function to the app/vmselect/netstorage package. 

It should accept search query as argument.

2024-09-05 16:31 UTC, f41gh7 requested changes
please see comments

2024-09-23 14:08 UTC, f41gh7 commented on app/vmselect/netstorage/tenant_filters.go
> +
// fast path
if len(tfs) == 0 {
 return tenants, tfs, nil
}

2024-09-23 14:17 UTC, f41gh7 commented on app/vmselect/netstorage/netstorage.go
> +	}
fast path for len(sq.TagFilterss) == 0

2024-09-23 14:17 UTC, f41gh7 commented on app/vmselect/netstorage/netstorage.go
> +	if err != nil {
Apply filters to search query tokens.

2024-09-23 14:51 UTC, f41gh7 commented on app/vmselect/promql/eval.go
>  func evalNumber(ec *EvalConfig, n float64) []*timeseries {
return previous behavior. There is no need to join authTokens.

2024-09-25 13:30 UTC, f41gh7 commented on app/vmselect/netstorage/netstorage.go
> +		case "vm_project_id":
should we add default with assert:

logger.Fatalf("BUG: unexpected labeName=%q",labelName) ?

2024-09-25 13:44 UTC, f41gh7 commented on app/vmselect/netstorage/netstorage.go
> +		logger.Panicf("BUG: missing TenantTokens in multi-tenant search query")
This assert looks a bit tricky to me.

 It's a common practice in go to use a nil slices.  And later after some refactoring TenantTokens could become nil slice.
 In this case vmselect may panic in runtime, if provided filters matches 0 tenants.

 I think, it's better to remove this assert.

2024-09-25 13:56 UTC, f41gh7 commented on app/vmselect/netstorage/tenant_filters.go
> +func splitFiltersByType(tfs [][]storage.TagFilter) ([]string, [][]storage.TagFilter) {
I think, it's better to keep filters signature as is:

`func splitFiltersByType(tfs [][]storage.TagFilter) ([]storage.TagFilter, [][]storage.TagFilter)`

And convert TagFilter at `applyFiltersToTenants`

2024-09-25 14:10 UTC, f41gh7 commented on lib/storage/search.go
> +func (sq *SearchQuery) MarshaWithoutTenant(dst []byte) []byte {
Looks like this change will break API compatibility. 

 Unmarshal requires Account and Project IDs:

```
	if len(src) < 4 {
		return src, fmt.Errorf("cannot unmarshal AccountID: too short src len: %d; must be at least %d bytes", len(src), 4)
	}
	sq.AccountID = encoding.UnmarshalUint32(src)
	src = src[4:]

	if len(src) < 4 {
		return src, fmt.Errorf("cannot unmarshal ProjectID: too short src len: %d; must be at least %d bytes", len(src), 4)
	}
```

2024-09-25 14:10 UTC, f41gh7 commented on lib/storage/search.go
>  func (sq *SearchQuery) Marshal(dst []byte) []byte {
This method is only used at tests. Looks like it could be removed

2024-09-26 08:22 UTC, f41gh7 approved these changes
LGTM

@valyala PTAL

2024-09-30 21:27 UTC, jetalone85 commented
Hi @zekker6, @valyala and @f41gh7!

Any chance we'll see these changes in the next release? Looks almost ready, right?

2024-09-30 21:29 UTC, zekker6 commented
Hi @jetalone85, I cann't commit on that but that is very likely to happen. I'm currently working on polishin support of `/export` endpoints, but the rest is already reviewed and approved.

2024-09-30 21:35 UTC, zekker6 commented
>  Any help needed with code review?

If you will be interested, I will publish the latest version which should properly support export APIs within the next few hours. I can publish a pre-build docker images for testing if you will have some time and would like to help with identifying any issues left there.
Also, you can try multi-tenant querying on our playground here  - [link](https://play-grafana.victoriametrics.com/explore?schemaVersion=1&panes=%7B%22pcw%22:%7B%22datasource%22:%22P8FF7EDDF703E5E58%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22up%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P8FF7EDDF703E5E58%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1&chunkNotFound). You can check it out and let me know if you'll find any issues there.

2024-09-30 23:51 UTC, zekker6 commented
The latest build for this PR: [victoriametrics/vmselect:heads-multitenant-queries-0-gd022c41682](https://hub.docker.com/layers/victoriametrics/vmselect/heads-multitenant-queries-0-gd022c41682/images/sha256-765176235b919333132c79438a69d5a42c671ce859e88bafa3f71740bc35c376?context=explore)
It was also deployed to sandbox and play environments for testing.

It seems to be passing all tests for the recently discovered issues such as export API support and proper deduplication handling. @f41gh7 PTAL when you'll have some time.

2024-10-01 09:40 UTC, hagen1778 approved these changes

2024-10-01 09:40 UTC, hagen1778 commented on docs/Cluster-VictoriaMetrics.md
>  since untrusted source may break per-tenant data by writing unwanted samples to arbitrary tenants.
"or get access to data of arbitrary tenants"

2024-10-01 09:40 UTC, hagen1778 commented on docs/Cluster-VictoriaMetrics.md
> +  -d 'extra_filters[]={vm_account_id="7",vm_project_id="9"}' \
what takes precedence here? 
Can I limit access to a subset of tenants via `extra_filters` but still allow filtering by tenant on query time? If yes, this is an important use case and should be reflected in here in the doc as well.

2024-10-01 10:32 UTC, f41gh7 commented on app/vmselect/netstorage/netstorage.go
> +		projectID := encoding.UnmarshalUint32(metricName[4:8])
This code is unsafe and fragile. It uses internal knowledge of storage.Metric marshal implementation. 

It's better to mutate metricName during results processing at RunParallel.

 `shouldConvertTenantToLabels` field could be added to the `Results` struct.

And be checked before calling callback at RunParallel.

2024-10-01 10:34 UTC, f41gh7 commented on app/vmselect/netstorage/netstorage.go
> +	suffix := make([]byte, 0)
It's better to rename suffix to suffixBuff and pre-allocate needed cap.

2024-10-01 14:37 UTC, merged

2024-10-01 14:37 UTC, f41gh7 commented
Thanks for contribution!