vmauth: reader pool to reduce gc & mem alloc
VictoriaMetrics/VictoriaMetrics pull request #6446
Opened 2024-06-09 03:52 UTC by shichanglin5

goto https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6445

2024-06-09 03:59 UTC, shichanglin5 commented
After the change:
1. If the request body is not completely cached to buf when the request failed due to write broken before, it cannot be retried. Now it is OK (read buf + stream)
2. reduce gc and memory allocation, observation and monitoring can see a significant improvement
<img width="1504" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/48707349/0c3f5135-36cf-4b8a-ac99-75597c8805f1">

2024-06-24 16:22 UTC, f41gh7 requested changes
Thanks for the pull request!

 Could you please rebase it to the master branch and target PR also for master branch.


 I have few minor comments, which should simplify code reading.

 Feel free to address this changes or we can create separate PR based on your changes with needed fixes

2024-06-24 16:23 UTC, f41gh7 commented on app/vmauth/main.go
> +		bufReader := bufPool.Get()
it's better to create helper get and put functions like: 

```go
var readTrackingBodyPool sync.Pool

func getReadTrackingBody(origin io.ReadCloser, b int) *readTrackingBody {
	bufSize := 1024
	if b > 0 {
		bufSize = b
	}
	v := readTrackingBodyPool.Get()
	if v == nil {
		rtb := &readTrackingBody{
			r:   origin,
			buf: make([]byte, 0, bufSize),
		}
		return rtb
	}
	rtb := v.(*readTrackingBody)
	rtb.r = origin
	rtb.buf = bytesutil.ResizeNoCopyMayOverallocate(rtb.buf, b)[:0]

	return rtb
}

func putReadTrackingBody(rtb *readTrackingBody) {
	rtb.reset()
	readTrackingBodyPool.Put(rtb)
}
```

2024-06-24 16:23 UTC, f41gh7 commented on app/vmauth/main.go
> +		bufReader := bufPool.Get()
it simplifies pool usage and always reset instance properties at put

2024-06-24 16:25 UTC, f41gh7 commented on app/vmauth/main.go
> +	} else if err != nil {
From reader point of view, it's better to check err != nil and perform fast path on specific error. 

 Like:
```go

if err != nil {
		if err == io.EOF {
			rtb.bufComplete = true
			return n, err
		}
		rtb.cannotRetry = true
	}
```

2024-06-24 16:46 UTC, f41gh7 commented on app/vmauth/main.go
> +				return 0, err
I'd suggest to always return number of bytes read:

```go
nr, err := rtb.readFromStream(p[nb:])
return nb + nr, err
```

2024-06-25 15:12 UTC, shichanglin5 commented
a new pr based on branch master: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6533

2024-06-25 15:12 UTC, closed without merging