Sorting graphite metrics by default
VictoriaMetrics/VictoriaMetrics pull request #6616
Opened 2024-07-09 13:32 UTC by rbizos

Multiple graphite functions rely on order to join metrics, since it can depend on vmstorage response order, this order is not deterministic. 

This follows https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5810

### Describe Your Change

This pull request adds an alphanumerical sort at each metrics query to make the result deterministic. This is the same behaviour as in graphite web as you can see [here](https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/datalib.py#L272)

2024-07-09 15:50 UTC, f41gh7 approved these changes
LGTM


 Could you please update changelog?

2024-07-10 14:03 UTC, hagen1778 reviewed
Thanks for the PR!
@rbizos would you mind adding tests to check the changes?

@rbizos @f41gh7 do you expect performance degradation that we should warn users about in the changelog?

2024-07-11 08:00 UTC, f41gh7 commented
@rbizos WDYT about proposed changes at comment above?

2024-07-11 08:00 UTC, f41gh7 requested changes
needed to address comment

2024-07-11 10:00 UTC, rbizos commented
Hello @f41gh7 and @hagen1778, thanks a lot for your quick answers, 

> Currently, it's possible that sorting will not work as expected if function uses concurrent processing of results . It should work at some primitive cases ("diff", "first", "last", "current", "pow" functions) . Graphite uses sequential data processing model.

You are right, this explains some behavior I observed, for instance the group function order not being deterministic.

I tested this with our queries that use AggregateSeriesLists that is indeed sequential. This will have a performance impact (I don't know how much, I could try to measure it a bit with bigger queries) I was thinking, something we can do is to only activate that when a certain header is present that can be set in the eval config ?

2024-07-12 12:45 UTC, hagen1778 commented
@rbizos thanks for detailed explanation. @f41gh7 your call here.

2024-07-12 15:50 UTC, f41gh7 commented
@hagen1778 @rbizos 

I guess sorting result is required mostly for some data visualization tools, such as grafana. In this case adding result sorting at render_api reply level looks better to me.

 There is already a condition for that - `maxDataPoints > 0` (grafana always adds maxDataPoints param). And this condition assumes that result must be sorted, but in fact it's not due to concurrent nature of some functions. 

 So adding sorting for this condition will have a minimal performance impact and add proper result visualization at grafana.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmselect/graphite/render_api.go#L117

 WDYT?

2024-07-12 16:04 UTC, rbizos commented
Having the sorting at the render level will not fix the AggregateSeriesLists issue we face I'm afraid, the issue is that we join 2 lists based on their corresponding elements, if the order is not deterministic, the function has random result :(

2024-07-12 16:33 UTC, f41gh7 commented
Get it, for me it's a bug with `aggregateSeriesLists`, `diffSeriesLists`, `multiplySeriesLists` implementation. 

  For example,  expression `aggregateSeriesLists(`series_list_1`, `series_list_2`, sum)` may produce random result for the following case:
 - `series_list_1` =  series_list [ {name=1, values=[1,2,3,4,5] }, {name=2, values=[6,7,8,9,10] }
 - `series_list_1` =  series_list [ {name=3, values=[31,32,33,34,35] }, {name=4, values=[46,47,48,49,410] }

 Because name=1, name=2 and name=3, name=4 could be shuffled inside lists.

 Adding sorting to `ssFirst` and `ssSecond` at function `aggregateSeriesList`  should fix it

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmselect/graphite/transform.go#L1371

 Also, our tests do not coverage this case properly.

2024-07-13 08:48 UTC, rbizos commented
I did not want to add implicit ordering in those functions as I did not want to assume the order. Some query could have non alphanumerical order for instance :disappointed:  .
Adding sorting there fixes the issue indeed but I would rather add explicit SortByNode in the query itself.

At this point I would say there is 2 courses of action:
- Add a warning in the documentation so that users add a sort function call when using aggregateSeriesList.
- Have a way to have a deterministic order by sorting the results from VMStorage and force sequential processing.

I fear that the second solution would add some complexity to the code though.

2024-07-17 11:23 UTC, f41gh7 commented
I agree, currently  adding `SortByName` or any other sorting function should be marked as workaround for this issue.

Unfortunately, there is no easy way to disable concurrent processing with current implementation.

2024-07-22 07:37 UTC, closed without merging

2024-07-22 07:37 UTC, rbizos commented
Thanks a lot for your time, sorry for the noise as the fix is much simpler. I think this is the good solution, otherwise it would have been a complex and quite fundamental change, for a bunch of functions this seems hardly necessary.