docs: stream aggregation updated structure, added common mistakes section
VictoriaMetrics/VictoriaMetrics pull request #6777
Opened 2024-08-07 16:02 UTC by AndrewChubatiuk

### Describe Your Changes

Please provide a brief description of the changes you made. Be as specific as possible to help others understand the purpose and impact of your modifications.

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

2024-08-09 14:13 UTC, func25 commented on docs/stream-aggregation/configuration/README.md
> +* [`keep_metric_names`](?selfref=true#keep_input_names) `(bool: false)` - instructs keeping the original metric names for the aggregated samples.
Is the link correct? the flag is `keep_metric_names` but refers to `#keep_input_names`

2024-08-09 14:13 UTC, func25 commented on docs/stream-aggregation/key-concepts.md
> +via `-remoteWrite.urlRelabelConfig` can be used for routing only selected metrics to each `-remoteWrite.url` destination.
```suggestion
1. **Aggregate incoming data and replicate to N destinations**. For this, one should configure `-streamAggr.config`
to aggregate the incoming data before replicating it to all the configured `-remoteWrite.url` destinations.
2. **Individually aggregate incoming data for each destination**. For this, one should configure `-remoteWrite.streamAggr.config`
for each `-remoteWrite.url` destination. [Relabeling](https://docs.victoriametrics.com/vmagent#relabeling) 
via `-remoteWrite.urlRelabelConfig` can be used for routing only selected metrics to each `-remoteWrite.url` destination.
```

2024-08-09 14:13 UTC, func25 commented on docs/stream-aggregation/key-concepts.md
> +It is possible specifying the exact list of labels in the output metrics via [`by`](./configuration/#by) list.
```suggestion
It is possible to specify the exact list of labels in the output metrics via [`by`](./configuration/#by) list.
```

2024-08-09 14:13 UTC, func25 commented on docs/stream-aggregation/troubleshooting.md
> +The following solutions can help reducing memory usage and CPU usage durting streaming aggregation:
```suggestion
The following solutions can help reduce memory usage and CPU usage during streaming aggregation:
```

2024-08-09 14:13 UTC, func25 commented on docs/stream-aggregation/use-cases.md
> +But this recording rule may take too much time to execute too. In this case the slow recording rule can be substituted
```suggestion
But this recording rule may take too much time to execute too. In this case, the slow recording rule can be substituted
```

2024-08-09 14:13 UTC, func25 commented on docs/stream-aggregation/use-cases.md
> +In this case the following stream aggregation can be used for reducing the number metrics stored in VictoriaMetrics:
```suggestion
In this case, the following stream aggregation can be used for reducing the number metrics stored in VictoriaMetrics:
```

2024-08-09 14:13 UTC, func25 commented on docs/stream-aggregation/use-cases.md
> +If the monitored application generates measurement metrics per each request, then it may be useful to calculate
```suggestion
If the monitored application generates measurement metrics per request, then it may be useful to calculate
```

2024-08-09 14:13 UTC, func25 commented on docs/stream-aggregation/use-cases.md
> +If the monitored application generates measurement metrics per each request, then it may be useful to calculate
```suggestion
If the monitored application generates measurement metrics per request, then it may be useful to calculate
```

2024-08-09 14:13 UTC, func25 commented on docs/vmagent.md
>  - The following command instructs `vmagent` to send only the last sample per each seen [time series](https://docs.victoriametrics.com/keyconcepts/#time-series) per every 60 seconds:
```suggestion
- The following command instructs `vmagent` to send only the last sample per each seen [time series](https://docs.victoriametrics.com/keyconcepts/#time-series) every 60 seconds:
```

2024-08-09 14:13 UTC, func25 commented on docs/stream-aggregation/use-cases.md
> +can be used for counting these metrics per every 30 second interval:
```suggestion
can be used for counting these metrics per 30 second interval:
```

2024-08-09 14:13 UTC, func25 commented on docs/stream-aggregation/use-cases.md
> +can be used for summing these metrics per every minute:
```suggestion
can be used for summing these metrics per minute:
```

2024-08-22 11:00 UTC, hagen1778 requested changes
Thanks for PR!

I see the following issues with these changes:
1. It breaks backward-compatibility with previously published links
2. The new menu structure has lower readability benefits compared to disadvantages caused by breaking the links. 
2.1 For example, KeyConcepts page isn't about key concepts, but just different aspects of aggregation. If the KeyConcepts needs to be added, it should contain a bit different information explaining the processing pipeline and specifics of time series aggregation.
2.2 Or CommonMistakes page should belong to Troubleshooting page


I like the new CommonMistakes page content, though. I think we should stick to the following principles in changing the docs:
1. Keep backward compatibility of the links. In some cases, we can keep the anchor in old docs and put a link to a new page. For example, we can move "Troubleshooting" and "Routing" (probably with rename) to submenu, as they contain low number of subsections and are logically separate to other content. 
2. Add submenus if they would actually contain de-coupled content from the main doc. For example, new Rerouting submenu could contain a more extensive description about what type of pipelines someone could build with vmagents. 

The new structure I propose is the following:
<img width="231" alt="image" src="https://github.com/user-attachments/assets/e9e40bbd-dced-480d-aa27-ba10e5ae53c8">

Here we move 2 sections to submenu. Both of these sections is easy to move without breaking compatibility. Both of them could have significant amount of content to be added in future. The new common mistakes page content I suggest to add to Troubleshooting submenu.

I'd like to move Config page as well, but it contains too many old links. So it is better to keep it as is.

I also propose to change main page structure to the following:
<img width="274" alt="image" src="https://github.com/user-attachments/assets/b16ac3b5-37cb-4382-8254-a7d2baaf3ca5">

The new structure puts important things first. And moves subtle details into 'Advanced usage' section. This should improve readbility of the doc.

wdyt @func25 @AndrewChubatiuk ?

2024-10-09 19:36 UTC, hagen1778 commented
Closing in favour of https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7202
Thanks for contribution @AndrewChubatiuk !

2024-10-09 19:36 UTC, closed without merging