vmui: add column search in table settings
VictoriaMetrics/VictoriaMetrics pull request #6804
Opened 2024-08-14 12:46 UTC by Loori-R

### Describe Your Changes

Add search functionality to the column display settings in the table
 #6668
 
![image](https://github.com/user-attachments/assets/e9bd52c3-6428-4d4f-8b7f-d83dd80b6912)

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

2024-08-14 12:55 UTC, dmitryk-dk approved these changes
LGTM!

2024-08-21 09:41 UTC, hagen1778 requested changes

2024-08-21 09:41 UTC, hagen1778 commented on docs/CHANGELOG.md
> +* FEATURE: [vmui](https://docs.victoriametrics.com/#vmui): add the ability to select all columns in the column display settings of the table. See [this issue](https://github.com/VictoriaMetrics/Victo
should this change be present in VictoriaLogs changelog as well?

2024-08-21 09:41 UTC, hagen1778 commented on app/vmui/packages/vmui/src/components/Table/TableSettings/TableSettings.tsx
> +                      checked={defaultColumns.length === columns.length}
Looks like this button should check or uncheck only filtered fields.
For example, if I filtered fields by search keyword and pressed check-all, I'd expect only the fields I see in the options to be checked. In fact, it checks all the fields.

2024-08-22 14:57 UTC, hagen1778 approved these changes
Thanks!

2024-08-22 14:57 UTC, merged