RegisterMetricNames does not create new per-day index entries for new dates for existing timeseries
VictoriaMetrics/VictoriaMetrics pull request #6872
Opened 2024-08-24 21:41 UTC by rtm0

### Describe Your Changes

Once the timeseries is in tsidCache, new entries won't be created in per-day index because the RegisterMetricNames() code does consider different dates for the same timeseries. So this case has been added.

The same bug exists for AddRows() but it is not manifested because the index entries are finally created in updatePerDateData().

RegisterMetricNames also updated to increase the newTimeseriesCreated counter because it actually creates new time series in index.

A unit tests has been added that check all possible data patterns (different metric names and dates) and code branches in both RegisterMetricNames and AddRows. The total number of new unit tests is around 100 which increaded the running time of storage tests by 50%. The PR #6871 should help here.

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

2024-08-26 15:07 UTC, hagen1778 commented
>Once the timeseries is in tsidCache, new entries won't be created in per-day index because the RegisterMetricNames() code does consider different dates for the same timeseries. So this case has been added.

@rtm0 do I understand it right that this bug is related only to Graphite https://graphite.readthedocs.io/en/stable/tags.html#adding-series-to-the-tagdb handler?

2024-08-26 16:37 UTC, rtm0 commented
> @rtm0 do I understand it right that this bug is related only to Graphite https://graphite.readthedocs.io/en/stable/tags.html#adding-series-to-the-tagdb handler?

@hagen1778, RegisterMetricNames() is currently used for Graphite only. So yes, you are right. I understand that it is a very narrow use case and the fix is of low importance. But this code is in the codebase and therefore needs to be maintained. Also it turns out that this code can be used for restoring per-day index after it was disabled and then enabled again (something I've been working on and is almost ready, I will send a pr once a few other pending ones a merged in)

 I'd also say that the unit test in this pr is even more important since it covers many different data patterns and code branches in both RegisterMetricNames() and AddRows(), since it allows to intoduce changes to these functions safely.

2024-08-27 10:03 UTC, hagen1778 requested changes
Looks good! Thanks for adding well described tests!

Could you please add a note to the [CHANGELOG](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/changelog/CHANGELOG.md#tip) with description of the bugfix? See other bugfixes from contributors for examples.

2024-08-27 10:31 UTC, rtm0 commented
> Looks good! Thanks for adding well described tests!

Thank you!

> Could you please add a note to the [CHANGELOG](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/changelog/CHANGELOG.md#tip) with description of the bugfix? See other bugfixes from contributors for examples.

Done.

2024-08-27 11:50 UTC, hagen1778 approved these changes
LGTM

2024-08-27 11:50 UTC, hagen1778 commented on docs/changelog/CHANGELOG.md
> +* BUGFIX: [Single-node VictoriaMetrics](https://docs.victoriametrics.com/) and `vmstorage` in [VictoriaMetrics cluster](https://docs.victoriametrics.com/cluster-victoriametrics/): Fixes registering m
```suggestion
* BUGFIX: [Single-node VictoriaMetrics](https://docs.victoriametrics.com/) and `vmstorage` in [VictoriaMetrics cluster](https://docs.victoriametrics.com/cluster-victoriametrics/): fix metric names registering in the per-day index for new dates for existing time series when making calls to `/tags/tagSeries` and `/tags/tagMultiSeries` handlers of [Grpahite API](https://docs.victoriametrics.com/#graphite-api-usage). See [this](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6872/) for details.
```

2024-08-27 12:11 UTC, rtm0 commented
Accepted the suggestion. Thanks!

2024-08-27 19:32 UTC, f41gh7 approved these changes
LGTM

2024-08-27 19:33 UTC, merged

2024-08-27 19:34 UTC, f41gh7 commented
Thanks for contribution!