feat: spread load of rule evaluation by group when starting new groups
VictoriaMetrics/VictoriaMetrics pull request #724
Opened 2020-08-26 09:48 UTC by dxtrzhang

spread load of rule evaluation by group

2020-08-26 09:52 UTC, dxtrzhang commented
FYI. This PR may make rule file reloading time even worse, see #691 and #704.
Pls resolve that PR first.

2020-09-01 12:54 UTC, valyala reviewed
LGTM overall. Please address the comment in order to reduce the resulting diff for this pull request.

2020-09-01 12:54 UTC, valyala commented on app/vmalert/group.go
> +		logger.Infof("sleep for %v, group %q started; interval=%v; concurrency=%d", time.Duration(randSleep), g.Name, g.Interval, g.Concurrency)
It would be better moving lines 198-201 below the `select` block. This should reduce the resulting diff.

2020-09-02 12:21 UTC, valyala approved these changes
LGTM.

@hagen1778 , could you look at the change and merge if it is OK?

2020-09-02 17:01 UTC, hagen1778 requested changes
Looks good! See my comments

2020-09-02 17:01 UTC, hagen1778 commented on app/vmalert/group.go
> +	logger.Infof("sleep for %v, group %q started; interval=%v; concurrency=%d", time.Duration(randSleep), g.Name, g.Interval, g.Concurrency)
```suggestion
	logger.Infof("group %q started with delay %v; interval=%v; concurrency=%d", time.Duration(randSleep), g.Name, g.Interval, g.Concurrency)
```

2020-09-02 21:58 UTC, merged

2020-09-02 22:01 UTC, valyala commented on app/vmalert/group.go
> +	// This should spread load of rule evaluation by group
Addressed these comments in 5f16ceb294946a48a65e958fa8acd91a2e266ad9

2020-09-02 22:03 UTC, valyala commented
@dxtrzhang , thanks for the contribution! Could you verify whether `vmalert` built from the commit 5f16ceb294946a48a65e958fa8acd91a2e266ad9 in `master` branch spreads group evaluation load over time as expected?

2020-09-03 02:15 UTC, dxtrzhang commented
works as expected！
Thanks for the update :)

2020-09-04 00:43 UTC, valyala commented
FYI, the feature has been included in [v1.40.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).