changed vmalert behaviour
VictoriaMetrics/VictoriaMetrics pull request #738
Opened 2020-09-02 13:23 UTC by f41gh7

added ability to start with empty rules directory

2020-09-02 13:53 UTC, valyala commented
@f41gh7 , could you extend commit message with the explanation why this change may be needed?

@hagen1778 , PTAL

2020-09-02 14:57 UTC, f41gh7 commented on app/vmalert/config/config.go
> +	"github.com/VictoriaMetrics/VictoriaMetrics/lib/logger"
done

2020-09-02 16:46 UTC, hagen1778 requested changes
LGTM! Pls note my comments

2020-09-02 16:46 UTC, hagen1778 commented on app/vmalert/config/config.go
> +
extra new line may be omitted

2020-09-02 16:46 UTC, hagen1778 commented on app/vmalert/manager_test.go
>  	m := &manager{groups: make(map[uint64]*Group)}
Please rename test to "TestManagerEmptyGroups" or similar to reflect the purpose of this test.

2020-09-02 16:46 UTC, hagen1778 commented on app/vmalert/manager_test.go
> +		t.Fatalf("expected to load succesfully with empty rules dir; got err instead: %v", err)
Please add a new test or a test case to `TestManagerUpdate` to verify that `vmalert` can be started with empty groups and then updated with existing ones.

2020-09-03 07:07 UTC, hagen1778 approved these changes

2020-09-03 08:04 UTC, valyala approved these changes

2020-09-03 08:04 UTC, merged