docs/vmanomaly: add self-monitoring section
VictoriaMetrics/VictoriaMetrics pull request #7558
Opened 2024-11-16 19:40 UTC by fred-navruzov

### Describe Your Changes

- Added self-monitoring guide for `vmanomaly`.
- Added cross-referencing on other pages.
- Slight improvements in wording on related pages
- TODO: publish Grafana dashboard to https://grafana.com/orgs/victoriametrics/dashboards

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

2024-11-17 02:12 UTC, tiny-pangolin requested changes
Please add link before merging

2024-11-17 12:02 UTC, fred-navruzov commented on docs/anomaly-detection/Self-monitoring.md
> +To visualize and interact with the self-monitoring metrics, `vmanomaly` provides a [Grafana Dashboard](#TODO-add-link). It offers an overview of service health (per job, instance) and performance met
correct, that's why this PR is still in DRAFT and I added TODO: for adding this link (right now I'm blocked to add it)

2024-11-17 12:06 UTC, fred-navruzov commented on docs/anomaly-detection/README.md
I couldn't make a better choice other than referencing our 1st article in a series (which itself has all the cross-references to other posts in series ToC), as long as I have to use 2 different tags to isolate such series (i.e. `vmanomaly` + `product updates`). Right now I know how to only reference 1 at a time, like https://victoriametrics.com/blog/categories/product-news/ or https://victoriametrics.com/blog/categories/anomaly-detection/ but not both

The only workaround I thought of is to create new (redundant) tag (i.e. `vmanomaly-updates`) and use it for reference, but that doesn't look good to me

2024-11-18 04:38 UTC, tiny-pangolin commented on docs/anomaly-detection/README.md
I think linking to https://victoriametrics.com/blog/categories/anomaly-detection/ would be a better idea in this case and update some of the tags on previous posts.

2024-11-18 04:47 UTC, tiny-pangolin commented on docs/anomaly-detection/Self-monitoring.md
> +To visualize and interact with the self-monitoring metrics, `vmanomaly` provides a [Grafana Dashboard](#TODO-add-link). It offers an overview of service health (per job, instance) and performance met
Thanks for fixing the link I think this good to merge for now There are a couple of bugs with the dashboard I imported from Grafana. I will update you in a different thread

2024-11-18 12:55 UTC, fred-navruzov commented on docs/anomaly-detection/README.md
thanks, I'll change to https://victoriametrics.com/blog/tags/anomaly-detection/ **tag**, as long as we don't have a **category** (as we have for `product-news`)

2024-11-18 18:12 UTC, tiny-pangolin approved these changes
looks good we can work on getting the vmanomaly tag added to the blog and updating docs at a later time.

2024-11-18 18:14 UTC, merged