app/vlinsert/datadog: support json in message field for serverless support
VictoriaMetrics/VictoriaMetrics pull request #7769
Opened 2024-12-09 10:30 UTC by AndrewChubatiuk

issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7761

### Describe Your Changes

datadog /api/v2/logs api supports message field in json format, which is not documented and used for serverless extension. This PR allows message field to be both string and object type

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

2024-12-20 15:52 UTC, f41gh7 commented on app/vlinsert/datadog/datadog.go
> +				switch v.Type() {
I suggest to add a new function:

```go
// datadog message field has two formats:
//   - regular log message with string text
//   - nested json format for serverless plugins
//     which has folowing format:
//     {"message": {"message": "text","lamdba": {"arn": "string","requestID": "string"}} }
//
// See https://github.com/DataDog/datadog-agent/blob/1c318b7c0025332108f8d45192ffd6069b5331b5/pkg/logs/processor/json_serverless.go#L25
func appendMsgFields(fields []logstorage.Field, v *fastjson.Value) ([]logstorage.Field, error) {
	switch v.Type() {
	case fastjson.TypeString:
		val := v.GetStringBytes()
		fields = append(fields, logstorage.Field{
			Name:  "_msg",
			Value: bytesutil.ToUnsafeString(val),
		})
	case fastjson.TypeObject:
		var firstErr error
		v.GetObject().Visit(func(k []byte, v *fastjson.Value) {
			if firstErr != nil {
				return
			}
			switch string(k) {
			case "message":
				val := v.GetStringBytes()
				fields = append(fields, logstorage.Field{
					Name:  "_msg",
					Value: bytesutil.ToUnsafeString(val),
				})
			case "lamdba":
				obj, err := v.Object()
				if err != nil {
					firstErr = err
					firstErr = fmt.Errorf("unexpected lambda value type for %q:%q; want object", k, v)
					return
				}
				obj.Visit(func(k []byte, v *fastjson.Value) {
					if firstErr != nil {
						return
					}
					val, err := v.StringBytes()
					if err != nil {
						firstErr = fmt.Errorf("unexpected lambda label value type for %q:%q; want string", k, v)
						return
					}
					fields = append(fields, logstorage.Field{
						Name:  bytesutil.ToUnsafeString(k),
						Value: bytesutil.ToUnsafeString(val),
					})
				})

			}
		})
	default:
		return fields, fmt.Errorf("unsupported message type %q", v.Type().String())
	}
	return fields, nil
}
```

 and use it as:

```go
			switch bytesutil.ToUnsafeString(k) {
			case "message":
				fields, err = appendMsgFields(fields, v)
				if err != nil {
					return
				}
```

2024-12-20 15:54 UTC, f41gh7 commented on app/vlinsert/datadog/datadog.go
> +					logstorage.PutJSONParser(p)
given code violates `ParseLogMessage` rule. It holds reference for p.Fields after `PutJSONParser` call.

2024-12-20 15:55 UTC, f41gh7 requested changes
Overall looks good. Please see comments

2024-12-20 17:13 UTC, AndrewChubatiuk commented
hey @f41gh7 
thanks for review
addressed your comments

2024-12-23 08:56 UTC, f41gh7 approved these changes
LGTM

2024-12-23 08:57 UTC, merged

2024-12-23 08:57 UTC, f41gh7 commented
Thanks for contribution!