lib/promscrape: added label_limit global and per job scrape param
VictoriaMetrics/VictoriaMetrics pull request #7795
Opened 2024-12-11 09:42 UTC by AndrewChubatiuk

### Describe Your Changes

related issues:
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7660
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3233

with this change suggestion for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3233 is to
- set maxLabelsPerTimeseries either to 0 or to maximum expected value
- set a global scrape configuration `label_limit` to a default value for scrape configuration
- override on certain jobs global default for `label_limit` with a value, that is up to maxLabelsPerTimeseries if it's defined

this will allow avoid propagation of custom labelLimits into tryPush agent's function

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

2025-03-11 13:52 UTC, f41gh7 commented on lib/promscrape/scrapework.go
>  	sw.addRowToTimeseries(wc, &sw.tmpRow, timestamp, false)
As far as I see, this method may fail as well and there is no check for it.

2025-03-11 13:52 UTC, f41gh7 commented on lib/promscrape/scrapework.go
> +func (sw *scrapeWork) addRowToTimeseries(wc *writeRequestCtx, r *parser.Row, timestamp int64, needRelabel bool) bool {
Should it be renamed to `tryAddRowToTimeseries` ?

2025-03-11 14:47 UTC, AndrewChubatiuk commented on lib/promscrape/scrapework.go
> +		trackIgnoredSeriesWithTooManyLabels(wc.labels[:labelsLen], labelLimit)
updated

2025-03-11 14:47 UTC, AndrewChubatiuk commented on lib/promscrape/scrapework.go
> +func (sw *scrapeWork) addRowToTimeseries(wc *writeRequestCtx, r *parser.Row, timestamp int64, needRelabel bool) bool {
updated

2025-03-11 14:49 UTC, AndrewChubatiuk commented on lib/promscrape/scrapework.go
>  	sw.addRowToTimeseries(wc, &sw.tmpRow, timestamp, false)
this method will work as it used to work before, as it has needRelabel arg set to false

2025-06-04 13:32 UTC, hagen1778 commented
@AndrewChubatiuk kindly pinging you on this

2025-06-10 13:32 UTC, AndrewChubatiuk commented on lib/promscrape/scrapework.go
> +		}
@hagen1778 updated PR

2025-06-18 13:38 UTC, AndrewChubatiuk commented
@hagen1778 please review it

2025-06-19 14:17 UTC, hagen1778 requested changes

2025-06-19 14:17 UTC, hagen1778 commented on lib/promscrape/scrapework.go
> +		return false
This changes the behavior. If before series with no labels were just ignored, now the whole scrape will be rejected. And it will be rejected with false error "the response from %q exceeds label_limit..."

I'd suggest to change tryAddRow signature to return error. Then caller can differentiate between actual errors and nils

2025-06-19 14:17 UTC, hagen1778 commented on lib/promscrape/scrapework.go
> +	}
this logic can be moved inside tryAddRows, as we changing its singature anyway. If we do this and tryAddRows will start returning err, the processing will become much more simpler:
```
	err := wc.tryAddRows(cfg, wc.rows.Rows, scrapeTimestamp, true)
	if err != nil {
		scrapesSkippedBySampleLimit.Inc()
		wc.writeRequest.Reset()
		up = 0
	}
```

2025-06-24 13:07 UTC, hagen1778 commented
@AndrewChubatiuk @makasim please see the following updates:
* https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7795/commits/34e2a5520bfffc7a2db9ac5a805a9b29422275df
* https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7795/commits/797ed0d5ad036fa56c7e467648d46e70e2a17441
* https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7795/commits/5c51d3c70351d61ca44ac7f898b36561b61332bf
* https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7795/commits/22f855c9ccfb755b4912bc5675a3637d00853172
* https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7795/commits/f75ef8a89aa7ff882c4641f0a2873bca83507eda
* https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7795/commits/83fca46dd07fb222002b4ec82dd7fe78335ca2aa

I need approve from you to merge this PR

2025-06-26 08:22 UTC, makasim commented on docs/victoriametrics/sd_configs.md
> +  # label_limit: <int>
Why not use `labels_limit` for consistency with `series_limit` param and `scrape_labels_limit` metric?

2025-06-26 08:23 UTC, hagen1778 commented on docs/victoriametrics/sd_configs.md
> +  # label_limit: <int>
For consistency with `label_limit` from Prometheus https://prometheus.io/docs/prometheus/latest/configuration/configuration/ 
```
# Limit on the number of labels that will be accepted per sample. If more
  # than this number of labels are present on any sample post metric-relabeling,
  # the entire scrape will be treated as failed. 0 means no limit.
  [ label_limit: [<int>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#int) | default = 0 ]
```

2025-06-26 08:27 UTC, makasim commented on docs/victoriametrics/sd_configs.md
> +  # label_limit: <int>
Thanks, that makes sense. In that case, should we rename the metric `scrape_labels_limit` to `scrape_label_limit` for consistency?

2025-06-26 09:08 UTC, makasim commented on lib/promscrape/scrapework.go
> +				return fmt.Errorf("the response from %q exceeds label_limit=%d; "+
```suggestion
				return fmt.Errorf("the response from %q  contains samples with a number of labels exceeding label_limit=%d; "+
```

2025-06-26 09:56 UTC, makasim commented on lib/promscrape/scrapework.go
> +			if errors.Is(err, errLabelsLimitExceeded) {
Currently, the error handling logic only works in streaming mode. I think it should also be applied to `processDataOneShot`.

2025-06-26 10:10 UTC, makasim commented on lib/promscrape/scrapework.go
> +			if errors.Is(err, errLabelsLimitExceeded) {
What was the purpose of errLabelsLimitExceeded?

From my perspective, it could be removed entirely, the error message could be constructed directly in the `tryAddRow` function, where all the necessary information is already available. In this case, there is no need to handle the error separately in streaming and one-shot mode.

2025-06-26 10:27 UTC, makasim commented on lib/promscrape/scrapework.go
> +	if needRelabel && labelLimit > 0 && len(wc.labels)-labelsLen > labelLimit {
It does not work as described in [prometheus doc](https://prometheus.io/docs/prometheus/latest/configuration/configuration/):

```
# Limit on the number of labels that will be accepted per sample. If more
  # than this number of labels are present on any sample post metric-relabeling,
  # the entire scrape will be treated as failed. 0 means no limit.
  [ label_limit: [<int>](https://prometheus.io/docs/prometheus/latest/configurati
```

here's my config:

```yaml
scrape_configs:
  - job_name: demo-app
    label_limit: 10
    #stream_parse: true
    static_configs:
      - targets:
          - localhost:8080
```

This scrape passes:
```
demo_counter_total{a1="1",b1="2",c1="3",d1="4",e1="5"}
demo_counter_total_2{a2="1",b2="2",c2="3",d2="4",e2="5",f2="6",g2="7",h2="8"}
```

This hits the label limit:
```
demo_counter_total{a1="1",b1="2",c1="3",d1="4",e1="5"}
demo_counter_total_2{a2="1",b2="2",c2="3",d2="4",e2="5",f2="6",g2="7",h2="8",i2="9"}
```

But I expected that it should fail only if I added two more labels.

2025-06-26 10:33 UTC, AndrewChubatiuk commented on lib/promscrape/scrapework.go
> +	if needRelabel && labelLimit > 0 && len(wc.labels)-labelsLen > labelLimit {
need to take into account metric name as well

2025-06-26 11:55 UTC, hagen1778 commented on docs/victoriametrics/sd_configs.md
> +  # label_limit: <int>
hard to say :) 
https://github.com/VictoriaMetrics/VictoriaMetrics/commit/22f855c9ccfb755b4912bc5675a3637d00853172

2025-06-26 11:58 UTC, hagen1778 commented on lib/promscrape/scrapework.go
> +			if errors.Is(err, errLabelsLimitExceeded) {
I added it for one reason only: bring up error processing to the same level as `SampleLimit`. To keep the metric increment logic and scrape discard logic close to each other.
Otherwise, it is unclear why `func (wc *writeRequestCtx) tryAddRow` has anything to do with `scrapesSkippedByLabelLimit` metric, as it might be used out of scrape context.

2025-06-26 12:04 UTC, hagen1778 commented on lib/promscrape/scrapework.go
> +			if errors.Is(err, errLabelsLimitExceeded) {
> Currently, the error handling logic only works in streaming mode. I think it should also be applied to processDataOneShot.

Thanks! I've updated it at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7795/commits/d694128569c52938789da314c2232630a9716b97

2025-06-26 12:17 UTC, makasim commented on lib/promscrape/scrapework.go
> +			if errors.Is(err, errLabelsLimitExceeded) {
~~I see, but the cases are a bit different. In the case of the samples limit, the if condition, metric increment, and error logging are all in one place. However, for the label limit, the locality is worse—the condition is in one place, while the logging and metric increment are in another. In my opinion, it would be better to keep them together in one place for consistency and readability.~~

2025-06-26 14:01 UTC, makasim commented on docs/victoriametrics/sd_configs.md
> +  # label_limit: <int>
> hard to say :)

IMO it's better to be consistent between the parameter and its metric. So, series_limit has scrape_series_limit metric while label_limit should have scrape_label_limit option.

2025-06-26 14:15 UTC, hagen1778 commented on lib/promscrape/scrapework.go
> +	if needRelabel && labelLimit > 0 && len(wc.labels)-labelsLen > labelLimit {
@makasim the labels limit is applied after extra labels were added to the series. Extra labels that are always added during scraping are `instance` and `job`. So you need to account for 2 extra labels. And as @AndrewChubatiuk said, metric name is also a label.

2025-06-26 14:22 UTC, makasim approved these changes
LGTM

2025-06-27 12:14 UTC, f41gh7 commented on lib/promscrape/scrapework.go
> +func (wc *writeRequestCtx) tryAddRows(cfg *ScrapeWork, rows []parser.Row, timestamp int64, needRelabel bool) error {
I think, it's better to keep `addRows` naming and just add error. 

 `try` prefix is better to use with some boolean return result.

2025-06-27 12:15 UTC, f41gh7 commented on lib/promscrape/scrapework.go
> +var errLabelsLimitExceeded = errors.New("label_limit exceeded")
should we also add errSampleLimitExceeded for consistency?

2025-06-27 12:17 UTC, f41gh7 commented on lib/promscrape/scrapework.go
> +	if needRelabel && labelLimit > 0 && len(wc.labels)-labelsLen > labelLimit {
It's unclear why labelLimit check should be applied only if `needRelabel` is set.  I suggest to remove this implicit dependency.

2025-06-27 12:19 UTC, f41gh7 commented on lib/promscrape/scrapework.go
> +	_ = wc.tryAddRows(sw.Config, dst, timestamp, false)
If it's impossible case, please add assert: `logger.Fatalf("BUG: tryAddRows cannot return error for autoMetrics`.

2025-07-03 12:38 UTC, hagen1778 commented on lib/promscrape/scrapework.go
> +func (wc *writeRequestCtx) tryAddRows(cfg *ScrapeWork, rows []parser.Row, timestamp int64, needRelabel bool) error {
renamed

2025-07-03 12:40 UTC, hagen1778 commented on lib/promscrape/scrapework.go
> +var errLabelsLimitExceeded = errors.New("label_limit exceeded")
I don't see how to use it.
The problem of error handling here is that sample limit is checked differently in stream and oneShot processing. 
If not the stream apporach with using atomic counter, I could process errors in `addRow` functions:
1. no custom errors
2. faster abort if limits are breached
but because of the stream processing the samples limit can be checked only at the very end, after all `addRow` were finished. This makes code looks much more verbose than it should be. If you have good ideas how to refactor it - I am all ears.

2025-07-03 12:40 UTC, hagen1778 commented on lib/promscrape/scrapework.go
> +	if needRelabel && labelLimit > 0 && len(wc.labels)-labelsLen > labelLimit {
Tx, updated

2025-07-03 12:41 UTC, hagen1778 commented on lib/promscrape/scrapework.go
> +	_ = wc.tryAddRows(sw.Config, dst, timestamp, false)
updated

2025-07-03 15:09 UTC, f41gh7 commented on lib/promscrape/scrapework.go
> +	_ = wc.tryAddRows(sw.Config, dst, timestamp, false)
Looks like, it's possible to breach this limit and get panic.

  There is a problem, we can either: apply labels limit to auto-metrics as well and log it as error. Or ignore labels limit for it.

 I think we should go with 1 option. Next hope storage can apply own limits and drop auto metrics as well.

2025-07-04 07:04 UTC, hagen1778 commented on lib/promscrape/scrapework.go
> +	_ = wc.tryAddRows(sw.Config, dst, timestamp, false)
> apply labels limit to auto-metrics as well and log it as error

did this. see updated

2025-07-04 07:54 UTC, f41gh7 approved these changes
LGTM

2025-07-04 07:59 UTC, AndrewChubatiuk commented on lib/promscrape/scrapework_test.go
> +func TestWriteRequestCtx_TryAddRowNoRelabeling(t *testing.T) {
```suggestion
func TestWriteRequestCtx_AddRowNoRelabeling(t *testing.T) {
```

2025-07-04 08:18 UTC, merged

2025-07-04 08:18 UTC, f41gh7 commented
Thanks for contribution!