docs/vmanomaly: deprecate Overview page
VictoriaMetrics/VictoriaMetrics pull request #7812
Opened 2024-12-12 16:04 UTC by Cambaza

### Describe Your Changes

-Deprecate Overview page in Anomaly Detection docs. 
- Adding service description  to `README.md`
- Moving Licensing information to Quickstart page

### Checklist

The following checks are **mandatory**:

- [x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

2024-12-13 15:46 UTC, tenmozes requested changes
please add alias for this page to any existing page

2024-12-13 16:34 UTC, tenmozes approved these changes

2024-12-16 10:47 UTC, fred-navruzov reviewed
Please be careful and fix all (now misleading) links than previously mentioned `/anomaly-detection/overview/#some-anchor-name`, as well as for **renamed** sections of deleted page. Also, I'd suggest explicit renaming (do not rely solely on redirects, i.e. change all links having /anomaly-detection/overview/... to appropriate new destination:
- on components/models page (2):
```
Please find more detailed instructions (license, etc.) [here](https://docs.victoriametrics.com/anomaly-detection/overview/#run-vmanomaly-docker-container)
```
```
This section covers the `Models` component of VictoriaMetrics Anomaly Detection (commonly referred to as [`vmanomaly`](https://docs.victoriametrics.com/anomaly-detection/overview/)) and provides a guide on how to configure the service.
```

On guides/vmalert-guide (4):
```
*VictoriaMetrics Anomaly Detection* ([vmanomaly](https://docs.victoriametrics.com/anomaly-detection/overview/)) is a service that continuously scans time series stored in VictoriaMetrics and detects unexpected changes within data patterns in real-time. It does so by utilizing user-configurable machine learning models.
```
```
- Configure docker-compose file with all needed services ([VictoriaMetrics Single-Node](https://docs.victoriametrics.com/single-server-victoriametrics), [vmalert](https://docs.victoriametrics.com/vmalert/), [vmagent](https://docs.victoriametrics.com/vmagent/), [Grafana](https://grafana.com/), [Node Exporter](https://prometheus.io/docs/guides/node-exporter/) and [vmanomaly](https://docs.victoriametrics.com/anomaly-detection/overview/) ).
  - Explore configuration files for [vmanomaly](https://docs.victoriametrics.com/anomaly-detection/overview/) and [vmalert](https://docs.victoriametrics.com/vmalert/).
```

```
For additional licensing options, please refer to the [VictoriaMetrics Anomaly Detection documentation on licensing](https://docs.victoriametrics.com/anomaly-detection/overview/#licensing).
```
guides/readme (1)
```
This section holds guides of how to set up and use VictoriaMetrics Anomaly Detection (or simply [`vmanomaly`](https://docs.victoriametrics.com/anomaly-detection/overview/)) service, integrating it with different observability components.
```

2024-12-17 11:45 UTC, Cambaza commented on docs/anomaly-detection/QuickStart.md
> +For service introduction visit [README](https://docs.victoriametrics.com/anomaly-detection/) page.
All fixes have been implemented

2024-12-17 11:45 UTC, merged