bugfixed, the data time precision loss
VictoriaMetrics/VictoriaMetrics pull request #7848
Opened 2024-12-17 03:31 UTC by worker24h

### Describe Your Changes

Related Issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7830

### Checklist

The following checks are **mandatory**:

- [ ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).

2024-12-19 13:07 UTC, Loori-R reviewed
Adding `.000` and `.999` as strings is not a good approach because it can break if the data type or timestamp format changes. It's better to use `dayjs` methods like `startOf('second')` and `endOf('second')` for clarity and reliability.

2024-12-20 09:03 UTC, worker24h commented
> Adding `.000` and `.999` as strings is not a good approach because it can break if the data type or timestamp format changes. It's better to use `dayjs` methods like `startOf('second')` and `endOf('second')` for clarity and reliability.

Thanks your advise, I had changed it. @Loori-R please review the code again.

2024-12-20 10:32 UTC, Loori-R approved these changes
LGTM!

2024-12-28 06:23 UTC, worker24h commented
hi who could merge this PR

2025-01-07 13:58 UTC, hagen1778 requested changes
Hello @worker24h ! Would you mind adding the appropriate changelog line according to https://docs.victoriametrics.com/contributing/#pull-request-checklist ?

2025-01-08 11:18 UTC, worker24h commented
> Hello @worker24h ! Would you mind adding the appropriate changelog line according to https://docs.victoriametrics.com/contributing/#pull-request-checklist ?

@hagen1778 OK. I had a change log and added commit sign, could you check it?

2025-01-17 02:06 UTC, worker24h commented
@hagen1778 @Loori-R @dmitryk-dk Could you review it ?

2025-01-17 10:39 UTC, hagen1778 commented
Please see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7830#issuecomment-2597954759

2025-01-17 10:39 UTC, closed without merging